CREATE TABLE [dbo].[SALES]
(
	[SALE_DATE] DATE NOT NULL PRIMARY KEY,
	[PRICE_PAID] MONEY NOT NULL,
	[CD_ID] VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES CDS,
	[C_NUMBER] INT NOT NULL FOREIGN KEY REFERENCES CUSTOMER
)
